/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import {NativeEventEmitter, Platform, StyleSheet, Text, Button, View } from 'react-native';
import {RNPaytabsLibrary, PaymentSDKConfiguration, PaymentSDKBillingDetails} from '@paytabscom/react-native-paytabs-emulator';

// Prepare Paypage events for IOS
// const eventPreparePaypageEmitter = new NativeEventEmitter(RNPaytabsLibrary);
// const subscription = eventPreparePaypageEmitter.addListener(
//   'EventPreparePaypage',
//   (prepare) =>  RNPaytabsLibrary.log("eventPreparePaypageEmitter: " + prepare.action)
// );

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default class App extends Component {

  state = {
    message: '--'
  };
  
  constructor(props){
    super(props);
    this.state = { message: '' };
  }

  onPressPay(){
  
    let configuration = new PaymentSDKConfiguration();
    configuration.profileID = "49611"
    configuration.serverKey= "SMJNLTR2G6-JBGNGKBBM9-2MB6HGBG6M"
    configuration.clientKey = "CKKMDG-KDD262-TQTK22-GQGMHN"
    configuration.cartID = "545454"
    configuration.currency = "AED"
    configuration.cartDescription = "Flowers"
    configuration.merchantCountryCode = "ae"
    configuration.merchantName = "Sand Box"
    configuration.amount = 20
    configuration.screenTitle = "Pay with Card"

    let billingDetails = new PaymentSDKBillingDetails(name= "Mohamed Adly",
                                  email= "m.adly@paytabs.com",
                                  phone= "+201113655936",
                                  addressLine= "Flat 1,Building 123, Road 2345",
                                  city= "Dubai",
                                  state= "Dubai",
                                  countryCode= "AE",
                                  zip= "")
    configuration.billingDetails = billingDetails
    console.log(configuration)
    RNPaytabsLibrary.startCardPayment(JSON.stringify(configuration)).then( result => {
      //console.log(result)
     }, function(error) {
      //console.log(error)
     });
    // RNPaytabsLibrary.start(args, (response) => {
    //   RNPaytabsLibrary.log("on Response Payment");
    //   console.log(response);
    //   // Response Code: 100 successful otherwise fail
    //   if (response.pt_response_code == '100') {
    //     RNPaytabsLibrary.log("Transaction Id: " + response.pt_transaction_id);
    //     // Tokenization
    //   //RNPaytabs.log(response.pt_token_customer_email);
    //   //RNPaytabs.log(response.pt_token_customer_password);
    //   //RNPaytabs.log(response.pt_token);
    //   } else {
    //     RNPaytabsLibrary.log("Otherwise Response: " + response.pt_response_code);
    //   }
    //   this.state = { message: 'Result:' + response.pt_result };
    // });
  }
  onPressApplePay(){
    let configuration = new PaymentSDKConfiguration();
    configuration.profileID = "49611"
    configuration.serverKey= "SMJNLTR2G6-JBGNGKBBM9-2MB6HGBG6M"
    configuration.clientKey = "CKKMDG-KDD262-TQTK22-GQGMHN"
    configuration.cartID = "545454"
    configuration.currency = "AED"
    configuration.cartDescription = "Flowers"
    configuration.merchantCountryCode = "ae"
    configuration.merchantName = "Sand Box"
    configuration.amount = 20
    configuration.merchantIdentifier = "merchant.com.paytabs.applepay"

    RNPaytabsLibrary.startApplePayPayment(JSON.stringify(configuration)).then( result => {
      //console.log(result)
     }, function(error) {
      //console.log(error)
     });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to Paytabs Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button
            onPress={this.onPressPay}
            title="Pay with PayTabs"
            color="#c00"
          />
        <View style = {{height: 20}}></View>
        <Button
            onPress={this.onPressApplePay}
            title="Pay with Apple Pay"
            color="#c00"
            disabled = { Platform.OS != 'ios'}
          />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
