# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false

newArchEnabled=false

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

kotlinVersion=2.0.21
Paymentsdk_kotlinVersion=2.0.21
