source 'https://cdn.cocoapods.org/'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native/scripts/cocoapods/utils.rb'

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PaymentsdkExample' do
  use_react_native!(
    :path => "../node_modules/react-native",
    # Hermes is now enabled by default.
    :hermes_enabled => true
  )

  pod 'react-native-paymentsdk', :path => '../node_modules/@paytabs/react-native-paytabs'

  target 'PaymentsdkExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      "../node_modules/react-native",
      :mac_catalyst_enabled => false
    )
  end
end
