/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  ScrollView,
  TextInput,
  Switch,
  TouchableOpacity,
  Modal,
  FlatList,
  ActivityIndicator,
} from 'react-native';
import {
  RNPaymentSDKLibrary,
  PaymentSDKConfiguration,
  PaymentSDKBillingDetails,
  PaymentSDKShippingDetails,
  PaymentSDKSavedCardInfo,
  PaymentSDKNetworks,
} from '@paytabs/react-native-paytabs';
import { PaymentSDKConstants } from '../../lib/module';

const selectedNetworks = [
  PaymentSDKNetworks.VISA,
  PaymentSDKNetworks.MASTERCARD,
];

// Common currencies list
const currencies = [
  { code: 'AED', name: 'UAE Dirham' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'EGP', name: 'Egyptian Pound' },
  { code: 'USD', name: 'US Dollar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'KWD', name: 'Kuwaiti Dinar' },
  { code: 'BHD', name: 'Bahraini Dinar' },
  { code: 'OMR', name: 'Omani Rial' },
  { code: 'QAR', name: 'Qatari Riyal' },
  { code: 'JOD', name: 'Jordanian Dinar' },
  { code: 'LBP', name: 'Lebanese Pound' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'SEK', name: 'Swedish Krona' },
];

// Common country codes list
const countryCodes = [
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'EG', name: 'Egypt' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'OM', name: 'Oman' },
  { code: 'QA', name: 'Qatar' },
  { code: 'JO', name: 'Jordan' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'IN', name: 'India' },
  { code: 'JP', name: 'Japan' },
  { code: 'CN', name: 'China' },
  { code: 'AU', name: 'Australia' },
  { code: 'CA', name: 'Canada' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SE', name: 'Sweden' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'BE', name: 'Belgium' },
  { code: 'AT', name: 'Austria' },
  { code: 'SG', name: 'Singapore' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'PH', name: 'Philippines' },
];

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      message: '',
      isLoading: false,
      // Credentials
      profileID: '100181',
      serverKey: 'SRJNGJBG2D-JDRGZTMJBB-LHLJJBZJLB',
      clientKey: 'CBKMN9-Q2GP6D-RT97N6-72HNHM',
      merchantApplePayName: 'Your Store Name',
      merchantApplePayIdentifier: 'merchant.com.paytabs.applepay',
      // Payment Configuration
      showPaymentConfiguration: false,
      cartID: '1234',
      currency: 'EGP',
      cartDescription: 'Flowers',
      merchantCountryCode: 'EG',
      merchantName: 'Your Store Name',
      amount: '1.0',
      screenTitle: 'Pay with Card',
      expiryTime: '65',
      // Apple Pay Options
      simplifyApplePayValidation: true,
      forceShippingInfo: false,
      isDigitalProduct: false,
      enableZeroContacts: false,
      // Billing Details
      showBillingDetails: false,
      billingName: 'John Smith',
      billingEmail: 'email@test.com',
      billingPhone: '+97311111111',
      billingAddressLine: 'Street1',
      billingCity: 'Dubai',
      billingState: 'Dubai',
      billingCountryCode: 'ae',
      billingZip: '12345',
      // Shipping Details
      showShippingDetails: false,
      shippingName: 'John Smith',
      shippingEmail: 'email@test.com',
      shippingPhone: '+9731111111',
      shippingAddressLine: 'Street1',
      shippingCity: 'Dubai',
      shippingState: 'Dubai',
      shippingCountryCode: 'ae',
      shippingZip: '12345',
      // Currency Dropdown
      showCurrencyDropdown: false,
      // Merchant Country Code Dropdown
      showMerchantCountryCodeDropdown: false,
    };
  }

  // Validation helper functions
  validateEmail(email) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  validateRequiredFields() {
    const errors = [];

    if (!this.state.profileID || this.state.profileID.trim() === '') {
      errors.push('Profile ID is required');
    }
    if (!this.state.serverKey || this.state.serverKey.trim() === '') {
      errors.push('Server Key is required');
    }
    if (!this.state.clientKey || this.state.clientKey.trim() === '') {
      errors.push('Client Key is required');
    }
    if (!this.state.amount || parseFloat(this.state.amount) <= 0) {
      errors.push('Amount must be greater than 0');
    }
    if (!this.state.currency || this.state.currency.trim() === '') {
      errors.push('Currency is required');
    }

    return errors;
  }

  validateApplePay() {
    const errors = this.validateRequiredFields();

    // Validate Apple Pay specific fields
    const merchantID = this.state.merchantApplePayIdentifier
      .trim()
      .toLowerCase();
    if (!merchantID || merchantID === '') {
      errors.push(
        'Apple Pay Merchant ID is required. Please enter it in the Credentials section.'
      );
    }

    const merchantName = this.state.merchantApplePayName.trim();
    if (!merchantName || merchantName === '') {
      errors.push(
        'Apple Pay Merchant Name is required. Please enter it in the Credentials section.'
      );
    }

    return errors;
  }

  // Helper function to convert configuration to JSON
  configurationToJson(configuration) {
    const configJson = {
      profileID: configuration.profileID,
      serverKey: configuration.serverKey,
      clientKey: configuration.clientKey,
      cartID: configuration.cartID,
      currency: configuration.currency,
      cartDescription: configuration.cartDescription,
      merchantCountryCode: configuration.merchantCountryCode,
      merchantName: configuration.merchantName,
      amount: configuration.amount,
      screenTitle: configuration.screenTitle,
      expiryTime: configuration.expiryTime,
      showBillingInfo: configuration.showBillingInfo,
      showShippingInfo: configuration.showShippingInfo,
      paymentNetworks: configuration.paymentNetworks,
    };

    // Add Apple Pay specific fields if they exist
    if (configuration.merchantIdentifier !== undefined) {
      configJson.merchantIdentifier = configuration.merchantIdentifier;
    }
    if (configuration.simplifyApplePayValidation !== undefined) {
      configJson.simplifyApplePayValidation =
        configuration.simplifyApplePayValidation;
    }
    if (configuration.forceShippingInfo !== undefined) {
      configJson.forceShippingInfo = configuration.forceShippingInfo;
    }
    if (configuration.isDigitalProduct !== undefined) {
      configJson.isDigitalProduct = configuration.isDigitalProduct;
    }
    if (configuration.enableZeroContacts !== undefined) {
      configJson.enableZeroContacts = configuration.enableZeroContacts;
    }

    // Add billing details if present
    if (configuration.billingDetails) {
      configJson.billingDetails = {
        name: configuration.billingDetails.name,
        email: configuration.billingDetails.email,
        phone: configuration.billingDetails.phone,
        addressLine: configuration.billingDetails.addressLine,
        city: configuration.billingDetails.city,
        state: configuration.billingDetails.state,
        countryCode: configuration.billingDetails.countryCode,
        zip: configuration.billingDetails.zip,
      };
    }

    // Add shipping details if present
    if (configuration.shippingDetails) {
      configJson.shippingDetails = {
        name: configuration.shippingDetails.name,
        email: configuration.shippingDetails.email,
        phone: configuration.shippingDetails.phone,
        addressLine: configuration.shippingDetails.addressLine,
        city: configuration.shippingDetails.city,
        state: configuration.shippingDetails.state,
        countryCode: configuration.shippingDetails.countryCode,
        zip: configuration.shippingDetails.zip,
      };
    }

    return configJson;
  }

  // Generic payment handler
  handlePayment(paymentMethod, paymentFunction, successMessage) {
    try {
      // Validate required fields
      const validationErrors = this.validateRequiredFields();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({ isLoading: true, message: 'Processing payment...' });

      const configuration = this.buildConfiguration();
      const configJson = this.configurationToJson(configuration);

      console.log(
        `${paymentMethod} Configuration:`,
        JSON.stringify(configJson, null, 2)
      );

      paymentFunction(JSON.stringify(configJson))
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('Payment Details:', paymentDetails);
              this.setState({ message: successMessage });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error(`${paymentMethod} Error:`, error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: `Payment error: ${errorMessage}` });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error(`${paymentMethod} Exception:`, error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: `Payment exception: ${errorMessage}` });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: `Configuration error: ${errorMessage}` });
    }
  }

  buildConfiguration() {
    let configuration = new PaymentSDKConfiguration();

    // Credentials - trim whitespace
    configuration.profileID = this.state.profileID.trim();
    configuration.serverKey = this.state.serverKey.trim();
    configuration.clientKey = this.state.clientKey.trim();

    // Payment Configuration
    configuration.cartID = this.state.cartID;
    configuration.currency = this.state.currency;
    configuration.cartDescription = this.state.cartDescription;
    configuration.merchantCountryCode = this.state.merchantCountryCode;
    configuration.merchantName = this.state.merchantName.trim();
    configuration.amount = parseFloat(this.state.amount) || 0;
    configuration.screenTitle = this.state.screenTitle;
    configuration.expiryTime = parseInt(this.state.expiryTime, 10) || 0;

    // Billing Details - Only add if enabled
    if (this.state.showBillingDetails) {
      let billingDetails = new PaymentSDKBillingDetails(
        this.state.billingName,
        this.state.billingEmail,
        this.state.billingPhone,
        this.state.billingAddressLine,
        this.state.billingCity,
        this.state.billingState,
        this.state.billingCountryCode,
        this.state.billingZip
      );
      configuration.billingDetails = billingDetails;
      configuration.showBillingInfo = true;
    } else {
      configuration.showBillingInfo = false;
    }

    // Shipping Details
    if (this.state.showShippingDetails) {
      let shippingDetails = new PaymentSDKShippingDetails(
        this.state.shippingName,
        this.state.shippingEmail,
        this.state.shippingPhone,
        this.state.shippingAddressLine,
        this.state.shippingCity,
        this.state.shippingState,
        this.state.shippingCountryCode,
        this.state.shippingZip
      );
      configuration.shippingDetails = shippingDetails;
      configuration.showShippingInfo = true;
    } else {
      configuration.showShippingInfo = false;
    }

    configuration.paymentNetworks = selectedNetworks;

    return configuration;
  }

  onPressPay() {
    // Validate card payment
    const validationErrors = this.validateRequiredFields();
    if (validationErrors.length > 0) {
      this.setState({
        message: 'Validation errors: ' + validationErrors.join(', '),
        isLoading: false,
      });
      return;
    }

    this.handlePayment(
      'Card Payment',
      (config) => RNPaymentSDKLibrary.startCardPayment(config),
      'Payment successful!'
    );
  }

  onPressTokenizedPayment() {
    try {
      const validationErrors = this.validateRequiredFields();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({
        isLoading: true,
        message: 'Processing tokenized payment...',
      });

      const configuration = this.buildConfiguration();
      const configJson = this.configurationToJson(configuration);

      RNPaymentSDKLibrary.startTokenizedCardPayment(
        JSON.stringify(configJson),
        'Token',
        'TransactionReference'
      )
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('Tokenized Payment Details:', paymentDetails);
              this.setState({ message: 'Tokenized payment successful!' });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error('Tokenized Payment Error:', error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: 'Payment error: ' + errorMessage });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error('Tokenized Payment Exception:', error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: 'Payment exception: ' + errorMessage });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: 'Configuration error: ' + errorMessage });
    }
  }

  onPress3DsPayment() {
    try {
      const validationErrors = this.validateRequiredFields();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({ isLoading: true, message: 'Processing 3DS payment...' });

      const configuration = this.buildConfiguration();
      const configJson = this.configurationToJson(configuration);
      let cardInfo = new PaymentSDKSavedCardInfo('4111 11## #### 1111', 'visa');

      RNPaymentSDKLibrary.start3DSecureTokenizedCardPayment(
        JSON.stringify(configJson),
        JSON.stringify(cardInfo),
        'Token'
      )
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('3DS Payment Details:', paymentDetails);
              this.setState({ message: '3DS payment successful!' });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error('3DS Payment Error:', error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: 'Payment error: ' + errorMessage });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error('3DS Payment Exception:', error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: 'Payment exception: ' + errorMessage });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: 'Configuration error: ' + errorMessage });
    }
  }

  onPressSavedCardPayment() {
    try {
      const validationErrors = this.validateRequiredFields();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({
        isLoading: true,
        message: 'Processing saved card payment...',
      });

      const configuration = this.buildConfiguration();
      const configJson = this.configurationToJson(configuration);

      RNPaymentSDKLibrary.startPaymentWithSavedCards(
        JSON.stringify(configJson),
        false
      )
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('Saved Card Payment Details:', paymentDetails);
              this.setState({ message: 'Saved card payment successful!' });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error('Saved Card Payment Error:', error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: 'Payment error: ' + errorMessage });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error('Saved Card Payment Exception:', error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: 'Payment exception: ' + errorMessage });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: 'Configuration error: ' + errorMessage });
    }
  }

  onPressApplePay() {
    try {
      // Validate Apple Pay configuration
      const validationErrors = this.validateApplePay();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({ isLoading: true, message: 'Processing Apple Pay...' });

      const configuration = this.buildConfiguration();

      // Apply Apple Pay specific configuration
      // Normalize merchant ID to lowercase (Apple Pay merchant IDs are case-sensitive and should be lowercase)
      const merchantID = this.state.merchantApplePayIdentifier
        .trim()
        .toLowerCase();
      const merchantName = this.state.merchantApplePayName.trim();

      configuration.merchantName = merchantName;
      configuration.merchantIdentifier = merchantID;
      configuration.simplifyApplePayValidation =
        this.state.simplifyApplePayValidation;
      configuration.forceShippingInfo = this.state.forceShippingInfo;
      configuration.isDigitalProduct = this.state.isDigitalProduct;
      configuration.enableZeroContacts = this.state.enableZeroContacts;

      const configJson = this.configurationToJson(configuration);
      configJson.merchantName = merchantName;
      configJson.merchantIdentifier = merchantID;
      configJson.simplifyApplePayValidation =
        this.state.simplifyApplePayValidation;
      configJson.forceShippingInfo = this.state.forceShippingInfo;
      configJson.isDigitalProduct = this.state.isDigitalProduct;
      configJson.enableZeroContacts = this.state.enableZeroContacts;

      console.log(
        'Apple Pay Configuration:',
        JSON.stringify(configJson, null, 2)
      );

      RNPaymentSDKLibrary.startApplePayPayment(JSON.stringify(configJson))
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('Apple Pay Details:', paymentDetails);
              this.setState({ message: 'Apple Pay successful!' });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error('Apple Pay Error:', error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: 'Payment error: ' + errorMessage });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error('Apple Pay Exception:', error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: 'Payment exception: ' + errorMessage });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: 'Configuration error: ' + errorMessage });
    }
  }

  onPressSTCPay() {
    try {
      const validationErrors = this.validateRequiredFields();
      if (validationErrors.length > 0) {
        this.setState({
          message: 'Validation errors: ' + validationErrors.join(', '),
          isLoading: false,
        });
        return;
      }

      this.setState({ isLoading: true, message: 'Processing STC Pay...' });

      const configuration = this.buildConfiguration();
      configuration.alternativePaymentMethods = [
        PaymentSDKConstants.AlternativePaymentMethod.stcPay,
      ];
      const configJson = this.configurationToJson(configuration);
      configJson.alternativePaymentMethods = [
        PaymentSDKConstants.AlternativePaymentMethod.stcPay,
      ];

      RNPaymentSDKLibrary.startAlternativePaymentMethod(
        JSON.stringify(configJson)
      )
        .then(
          (result) => {
            this.setState({ isLoading: false });
            if (result.PaymentDetails != null) {
              let paymentDetails = result.PaymentDetails;
              console.log('STC Pay Details:', paymentDetails);
              this.setState({ message: 'STC Pay successful!' });
            } else if (result.Event === 'CancelPayment') {
              console.log('Cancel Payment Event');
              this.setState({ message: 'Payment cancelled' });
            }
          },
          (error) => {
            this.setState({ isLoading: false });
            console.error('STC Pay Error:', error);
            const errorMessage =
              error?.message || error?.toString() || 'Unknown error';
            this.setState({ message: 'Payment error: ' + errorMessage });
          }
        )
        .catch((error) => {
          this.setState({ isLoading: false });
          console.error('STC Pay Exception:', error);
          const errorMessage =
            error?.message || error?.toString() || 'Unknown error';
          this.setState({ message: 'Payment exception: ' + errorMessage });
        });
    } catch (error) {
      this.setState({ isLoading: false });
      console.error('Configuration Error:', error);
      const errorMessage =
        error?.message || error?.toString() || 'Unknown error';
      this.setState({ message: 'Configuration error: ' + errorMessage });
    }
  }

  renderInputField(
    label,
    value,
    onChangeText,
    placeholder,
    keyboardType = 'default',
    secureTextEntry = false
  ) {
    return (
      <View style={styles.inputContainer}>
        <Text style={styles.inputLabel}>{label}</Text>
        <TextInput
          style={styles.input}
          value={value}
          onChangeText={onChangeText}
          placeholder={placeholder}
          keyboardType={keyboardType}
          placeholderTextColor="#999"
          secureTextEntry={secureTextEntry}
        />
      </View>
    );
  }

  renderCurrencyDropdown() {
    const selectedCurrency =
      currencies.find((c) => c.code === this.state.currency) || currencies[0];

    return (
      <View style={styles.inputContainer}>
        <Text style={styles.inputLabel}>Currency</Text>
        <TouchableOpacity
          style={styles.dropdown}
          onPress={() => this.setState({ showCurrencyDropdown: true })}
        >
          <Text style={styles.dropdownText}>
            {selectedCurrency.code} - {selectedCurrency.name}
          </Text>
          <Text style={styles.dropdownArrow}>▼</Text>
        </TouchableOpacity>

        <Modal
          visible={this.state.showCurrencyDropdown}
          transparent={true}
          animationType="slide"
          onRequestClose={() => this.setState({ showCurrencyDropdown: false })}
        >
          <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Select Currency</Text>
                <TouchableOpacity
                  onPress={() => this.setState({ showCurrencyDropdown: false })}
                  style={styles.modalCloseButton}
                >
                  <Text style={styles.modalCloseText}>✕</Text>
                </TouchableOpacity>
              </View>
              <FlatList
                data={currencies}
                keyExtractor={(item) => item.code}
                renderItem={({ item }) => (
                  <TouchableOpacity
                    style={[
                      styles.currencyItem,
                      this.state.currency === item.code &&
                        styles.currencyItemSelected,
                    ]}
                    onPress={() => {
                      this.setState({
                        currency: item.code,
                        showCurrencyDropdown: false,
                      });
                    }}
                  >
                    <Text
                      style={[
                        styles.currencyCode,
                        this.state.currency === item.code &&
                          styles.currencyCodeSelected,
                      ]}
                    >
                      {item.code}
                    </Text>
                    <Text
                      style={[
                        styles.currencyName,
                        this.state.currency === item.code &&
                          styles.currencyNameSelected,
                      ]}
                    >
                      {item.name}
                    </Text>
                    {this.state.currency === item.code && (
                      <Text style={styles.checkmark}>✓</Text>
                    )}
                  </TouchableOpacity>
                )}
              />
            </View>
          </View>
        </Modal>
      </View>
    );
  }

  renderMerchantCountryCodeDropdown() {
    const selectedCountry =
      countryCodes.find((c) => c.code === this.state.merchantCountryCode) ||
      countryCodes[0];

    return (
      <View style={styles.inputContainer}>
        <Text style={styles.inputLabel}>Merchant Country Code</Text>
        <TouchableOpacity
          style={styles.dropdown}
          onPress={() =>
            this.setState({ showMerchantCountryCodeDropdown: true })
          }
        >
          <Text style={styles.dropdownText}>
            {selectedCountry.code} - {selectedCountry.name}
          </Text>
          <Text style={styles.dropdownArrow}>▼</Text>
        </TouchableOpacity>

        <Modal
          visible={this.state.showMerchantCountryCodeDropdown}
          transparent={true}
          animationType="slide"
          onRequestClose={() =>
            this.setState({ showMerchantCountryCodeDropdown: false })
          }
        >
          <View style={styles.modalOverlay}>
            <View style={styles.modalContent}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Select Country Code</Text>
                <TouchableOpacity
                  onPress={() =>
                    this.setState({ showMerchantCountryCodeDropdown: false })
                  }
                  style={styles.modalCloseButton}
                >
                  <Text style={styles.modalCloseText}>✕</Text>
                </TouchableOpacity>
              </View>
              <FlatList
                data={countryCodes}
                keyExtractor={(item) => item.code}
                renderItem={({ item }) => (
                  <TouchableOpacity
                    style={[
                      styles.currencyItem,
                      this.state.merchantCountryCode === item.code &&
                        styles.currencyItemSelected,
                    ]}
                    onPress={() => {
                      this.setState({
                        merchantCountryCode: item.code,
                        showMerchantCountryCodeDropdown: false,
                      });
                    }}
                  >
                    <Text
                      style={[
                        styles.currencyCode,
                        this.state.merchantCountryCode === item.code &&
                          styles.currencyCodeSelected,
                      ]}
                    >
                      {item.code}
                    </Text>
                    <Text
                      style={[
                        styles.currencyName,
                        this.state.merchantCountryCode === item.code &&
                          styles.currencyNameSelected,
                      ]}
                    >
                      {item.name}
                    </Text>
                    {this.state.merchantCountryCode === item.code && (
                      <Text style={styles.checkmark}>✓</Text>
                    )}
                  </TouchableOpacity>
                )}
              />
            </View>
          </View>
        </Modal>
      </View>
    );
  }

  renderSection(title, enabled, onToggle, children) {
    return (
      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>{title}</Text>
          <Switch
            value={enabled}
            onValueChange={onToggle}
            trackColor={{ false: '#90caf9', true: '#2196F3' }}
            thumbColor={enabled ? '#ffffff' : '#f4f3f4'}
          />
        </View>
        {enabled && <View style={styles.sectionContent}>{children}</View>}
      </View>
    );
  }

  render() {
    return (
      <View style={styles.container}>
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={true}
        >
          <Text style={styles.welcome}>PayTabs Payment SDK</Text>
          <Text style={styles.subtitle}>Configure your payment settings</Text>

          {this.state.message ? (
            <View style={styles.messageContainer}>
              {this.state.isLoading && (
                <ActivityIndicator
                  size="small"
                  color="#2196F3"
                  style={styles.loadingIndicator}
                />
              )}
              <Text style={styles.messageText}>{this.state.message}</Text>
            </View>
          ) : null}

          {/* Credentials Section - Always visible, no switch */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Credentials</Text>
            <View style={styles.sectionContent}>
              {this.renderInputField(
                'Profile ID',
                this.state.profileID,
                (text) => this.setState({ profileID: text })
              )}
              {this.renderInputField(
                'Server Key',
                this.state.serverKey,
                (text) => this.setState({ serverKey: text }),
                '',
                'default',
                true
              )}
              {this.renderInputField(
                'Client Key',
                this.state.clientKey,
                (text) => this.setState({ clientKey: text }),
                '',
                'default',
                true
              )}
              {Platform.OS === 'ios' && (
                <>
                  {this.renderInputField(
                    'Apple Pay Merchant Name',
                    this.state.merchantApplePayName,
                    (text) => this.setState({ merchantApplePayName: text })
                  )}
                  {this.renderInputField(
                    'Apple Pay Merchant ID',
                    this.state.merchantApplePayIdentifier,
                    (text) =>
                      this.setState({ merchantApplePayIdentifier: text })
                  )}
                </>
              )}
            </View>
          </View>

          {/* Payment Configuration - With switch */}
          {this.renderSection(
            'Payment Configuration',
            this.state.showPaymentConfiguration,
            (value) => this.setState({ showPaymentConfiguration: value }),
            <>
              {this.renderInputField('Cart ID', this.state.cartID, (text) =>
                this.setState({ cartID: text })
              )}
              {this.renderCurrencyDropdown()}
              {this.renderInputField(
                'Cart Description',
                this.state.cartDescription,
                (text) => this.setState({ cartDescription: text })
              )}
              {this.renderMerchantCountryCodeDropdown()}
              {this.renderInputField(
                'Merchant Name',
                this.state.merchantName,
                (text) => this.setState({ merchantName: text })
              )}
              {this.renderInputField(
                'Amount',
                this.state.amount,
                (text) => this.setState({ amount: text }),
                '0',
                'numeric'
              )}
              {this.renderInputField(
                'Screen Title',
                this.state.screenTitle,
                (text) => this.setState({ screenTitle: text })
              )}
              {this.renderInputField(
                'Expiry Time (seconds)',
                this.state.expiryTime,
                (text) => this.setState({ expiryTime: text }),
                '0',
                'numeric'
              )}
              {Platform.OS === 'ios' && (
                <>
                  <View style={styles.switchContainer}>
                    <Text style={styles.switchLabel}>
                      Simplify Apple Pay Validation
                    </Text>
                    <Switch
                      value={this.state.simplifyApplePayValidation}
                      onValueChange={(value) =>
                        this.setState({ simplifyApplePayValidation: value })
                      }
                      trackColor={{ false: '#90caf9', true: '#2196F3' }}
                      thumbColor={
                        this.state.simplifyApplePayValidation
                          ? '#ffffff'
                          : '#f4f3f4'
                      }
                    />
                  </View>
                  <View style={styles.switchContainer}>
                    <Text style={styles.switchLabel}>Force Shipping Info</Text>
                    <Switch
                      value={this.state.forceShippingInfo}
                      onValueChange={(value) =>
                        this.setState({ forceShippingInfo: value })
                      }
                      trackColor={{ false: '#90caf9', true: '#2196F3' }}
                      thumbColor={
                        this.state.forceShippingInfo ? '#ffffff' : '#f4f3f4'
                      }
                    />
                  </View>
                  <View style={styles.switchContainer}>
                    <Text style={styles.switchLabel}>
                      Digital Product (Apple Pay)
                    </Text>
                    <Switch
                      value={this.state.isDigitalProduct}
                      onValueChange={(value) =>
                        this.setState({ isDigitalProduct: value })
                      }
                      trackColor={{ false: '#90caf9', true: '#2196F3' }}
                      thumbColor={
                        this.state.isDigitalProduct ? '#ffffff' : '#f4f3f4'
                      }
                    />
                  </View>
                  <View style={styles.switchContainer}>
                    <Text style={styles.switchLabel}>
                      Enable Zero Contacts (Apple Pay)
                    </Text>
                    <Switch
                      value={this.state.enableZeroContacts}
                      onValueChange={(value) =>
                        this.setState({ enableZeroContacts: value })
                      }
                      trackColor={{ false: '#90caf9', true: '#2196F3' }}
                      thumbColor={
                        this.state.enableZeroContacts ? '#ffffff' : '#f4f3f4'
                      }
                    />
                  </View>
                </>
              )}
            </>
          )}

          {/* Billing Details Section */}
          {this.renderSection(
            'Billing Details',
            this.state.showBillingDetails,
            (value) => this.setState({ showBillingDetails: value }),
            <>
              {this.renderInputField('Name', this.state.billingName, (text) =>
                this.setState({ billingName: text })
              )}
              {this.renderInputField(
                'Email',
                this.state.billingEmail,
                (text) => this.setState({ billingEmail: text }),
                'email@example.com',
                'email-address'
              )}
              {this.renderInputField(
                'Phone',
                this.state.billingPhone,
                (text) => this.setState({ billingPhone: text }),
                '+1234567890',
                'phone-pad'
              )}
              {this.renderInputField(
                'Address Line',
                this.state.billingAddressLine,
                (text) => this.setState({ billingAddressLine: text })
              )}
              {this.renderInputField('City', this.state.billingCity, (text) =>
                this.setState({ billingCity: text })
              )}
              {this.renderInputField('State', this.state.billingState, (text) =>
                this.setState({ billingState: text })
              )}
              {this.renderInputField(
                'Country Code',
                this.state.billingCountryCode,
                (text) => this.setState({ billingCountryCode: text })
              )}
              {this.renderInputField(
                'ZIP Code',
                this.state.billingZip,
                (text) => this.setState({ billingZip: text })
              )}
            </>
          )}

          {/* Shipping Details Section */}
          {this.renderSection(
            'Shipping Details',
            this.state.showShippingDetails,
            (value) => this.setState({ showShippingDetails: value }),
            <>
              {this.renderInputField('Name', this.state.shippingName, (text) =>
                this.setState({ shippingName: text })
              )}
              {this.renderInputField(
                'Email',
                this.state.shippingEmail,
                (text) => this.setState({ shippingEmail: text }),
                'email@example.com',
                'email-address'
              )}
              {this.renderInputField(
                'Phone',
                this.state.shippingPhone,
                (text) => this.setState({ shippingPhone: text }),
                '+1234567890',
                'phone-pad'
              )}
              {this.renderInputField(
                'Address Line',
                this.state.shippingAddressLine,
                (text) => this.setState({ shippingAddressLine: text })
              )}
              {this.renderInputField('City', this.state.shippingCity, (text) =>
                this.setState({ shippingCity: text })
              )}
              {this.renderInputField(
                'State',
                this.state.shippingState,
                (text) => this.setState({ shippingState: text })
              )}
              {this.renderInputField(
                'Country Code',
                this.state.shippingCountryCode,
                (text) => this.setState({ shippingCountryCode: text })
              )}
              {this.renderInputField(
                'ZIP Code',
                this.state.shippingZip,
                (text) => this.setState({ shippingZip: text })
              )}
            </>
          )}

          {/* Payment Buttons */}
          <View style={styles.buttonContainer}>
            <TouchableOpacity
              style={[
                styles.paymentButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={() => this.onPressPay()}
              disabled={this.state.isLoading}
            >
              {this.state.isLoading ? (
                <ActivityIndicator size="small" color="#ffffff" />
              ) : (
                <Text style={styles.buttonText}>Pay with Card</Text>
              )}
            </TouchableOpacity>

            <TouchableOpacity
              style={[
                styles.paymentButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={() => this.onPressTokenizedPayment()}
              disabled={this.state.isLoading}
            >
              <Text style={styles.buttonText}>Tokenized Payment</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[
                styles.paymentButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={() => this.onPress3DsPayment()}
              disabled={this.state.isLoading}
            >
              <Text style={styles.buttonText}>3DS Tokenized Payment</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[
                styles.paymentButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={() => this.onPressSavedCardPayment()}
              disabled={this.state.isLoading}
            >
              <Text style={styles.buttonText}>Saved Card Payment</Text>
            </TouchableOpacity>

            {Platform.OS === 'ios' && (
              <TouchableOpacity
                style={[
                  styles.paymentButton,
                  this.state.isLoading && styles.buttonDisabled,
                ]}
                onPress={() => this.onPressApplePay()}
                disabled={this.state.isLoading}
              >
                <Text style={styles.buttonText}>Apple Pay</Text>
              </TouchableOpacity>
            )}

            <TouchableOpacity
              style={[
                styles.paymentButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={() => this.onPressSTCPay()}
              disabled={this.state.isLoading}
            >
              <Text style={styles.buttonText}>STC Pay</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[
                styles.paymentButton,
                styles.cancelButton,
                this.state.isLoading && styles.buttonDisabled,
              ]}
              onPress={async () => {
                console.log('Cancel payment');
                setTimeout(() => {
                  RNPaymentSDKLibrary.cancelPayment();
                }, 3000);
              }}
              disabled={this.state.isLoading}
            >
              <Text style={styles.buttonText}>Cancel Payment</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e3f2fd',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  welcome: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 8,
    color: '#1565c0',
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 15,
    textAlign: 'center',
    color: '#1976d2',
    marginBottom: 24,
    fontWeight: '500',
  },
  messageContainer: {
    backgroundColor: '#bbdefb',
    padding: 14,
    borderRadius: 10,
    marginBottom: 24,
    borderLeftWidth: 5,
    borderLeftColor: '#2196F3',
    shadowColor: '#2196F3',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  messageText: {
    color: '#0d47a1',
    fontSize: 15,
    fontWeight: '500',
  },
  loadingIndicator: {
    marginRight: 8,
  },
  section: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginBottom: 20,
    padding: 20,
    shadowColor: '#2196F3',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#90caf9',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#90caf9',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1565c0',
    letterSpacing: 0.3,
  },
  sectionContent: {
    marginTop: 12,
  },
  inputContainer: {
    marginBottom: 18,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#424242',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#90caf9',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    backgroundColor: '#f5f9ff',
    color: '#212121',
    shadowColor: '#2196F3',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  dropdown: {
    borderWidth: 1.5,
    borderColor: '#90caf9',
    borderRadius: 12,
    padding: 14,
    backgroundColor: '#f5f9ff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#2196F3',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  dropdownText: {
    fontSize: 16,
    color: '#212121',
    flex: 1,
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#1976d2',
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#90caf9',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1565c0',
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCloseText: {
    fontSize: 18,
    color: '#666',
    fontWeight: 'bold',
  },
  currencyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  currencyItemSelected: {
    backgroundColor: '#e3f2fd',
  },
  currencyCode: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1565c0',
    width: 60,
  },
  currencyCodeSelected: {
    color: '#1976d2',
  },
  currencyName: {
    fontSize: 16,
    color: '#424242',
    flex: 1,
  },
  currencyNameSelected: {
    color: '#1565c0',
    fontWeight: '600',
  },
  checkmark: {
    fontSize: 20,
    color: '#4caf50',
    fontWeight: 'bold',
    marginLeft: 10,
  },
  buttonContainer: {
    marginTop: 24,
    marginBottom: 24,
  },
  paymentButton: {
    backgroundColor: '#2196F3',
    padding: 18,
    borderRadius: 12,
    marginBottom: 14,
    alignItems: 'center',
    shadowColor: '#2196F3',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#1976d2',
  },
  cancelButton: {
    backgroundColor: '#757575',
    borderColor: '#616161',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 8,
  },
  switchLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#424242',
    flex: 1,
    marginRight: 12,
  },
});
