export const PaymentSDKNetworks = {
  AMEX: 'amex',
  PAGO_BANCOMAT: 'pagoBancomat',
  BANCONTACT: 'bancontact',
  CARTES_BANCAIRES: 'cartesBancaires',
  CHINA_UNION_PAY: 'chinaUnionPay',
  DANKORT: 'dankort',
  DISCOVER: 'discover',
  EFTPOS: 'eftpos',
  ELECTRON: 'electron',
  ELO: 'elo',
  ID_CREDIT: 'idCredit',
  INTERAC: 'interac',
  JCB: 'JCB',
  MADA: 'mada',
  MAESTRO: 'maestro',
  MASTERCARD: 'masterCard',
  MIR: 'mir',
  PRIVATE_LABEL: 'privateLabel',
  QUIC_PAY: 'quicPay',
  SUICA: 'suica',
  VISA: 'visa',
  V_PAY: 'vPay',
  BARCODE: 'barcode',
  GIROCARD: 'girocard',
  WAON: 'waon',
  NANACO: 'nanaco',
  POST_FINANCE: 'postFinance',
  T_MONEY: 'tmoney',
  MEEZA: 'meeza',
};

module.exports = PaymentSDKNetworks;
